package saloonbooking;

import javax.swing.JOptionPane;

public class AdminViewGUI extends javax.swing.JFrame {

    private Admin admin;
    private static AdminViewGUI sharedInstance;

    public static void setSharedInstance(AdminViewGUI instance) {
        sharedInstance = instance;
    }

    public static AdminViewGUI getSharedInstance() {
        return sharedInstance;
    }

    public AdminViewGUI(Admin admin) {
        this.admin = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
private static Staff[] staffList = new Staff[10];
private static int staffIndex = 0;

private void deleteStaff() {
    String name = JOptionPane.showInputDialog(this, "Enter staff name to delete:");

    if (name == null || name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Invalid input!");
        return;
    }

    boolean found = false;

    for (int i = 0; i < staffIndex; i++) {
        if (staffList[i] != null && staffList[i].getName().equalsIgnoreCase(name)) {

            // shift array
            for (int j = i; j < staffIndex - 1; j++) {
                staffList[j] = staffList[j + 1];
            }

            staffList[staffIndex - 1] = null;
            staffIndex--;

            found = true;
            break;
        }
    }

    if (found) {
        JOptionPane.showMessageDialog(this, "Staff deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Staff not found!");
    }
}

private void addStaff() {
    String name = JOptionPane.showInputDialog(this, "Enter staff name:");
    String role = JOptionPane.showInputDialog(this, "Enter staff role:");

    if (name == null || role == null || name.isEmpty() || role.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Invalid input!");
        return;
    }

    if (staffIndex < staffList.length) {
        staffList[staffIndex] = new Staff(name, role);
        staffIndex++;
        JOptionPane.showMessageDialog(this, "Staff added successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Staff list is full!");
    }
}
private void displayStaff() {
    StringBuilder staffInfo = new StringBuilder();

    for (int i = 0; i < staffList.length; i++) {
        if (staffList[i] != null) {
            staffInfo.append("Name: ")
                     .append(staffList[i].getName())
                     .append(", Role: ")
                     .append(staffList[i].getRole())
                     .append("\n");
        }
    }

    if (staffInfo.length() == 0) {
        displayData_Area.setText("No staff available.");
    } else {
        displayData_Area.setText(staffInfo.toString());
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deleteDataButton = new javax.swing.JButton();
        AddDataButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayData_Area = new javax.swing.JTextArea();
        AddStaff = new javax.swing.JButton();
        DeleteStaff = new javax.swing.JButton();
        manageStaffTab = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();

        jTabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, null, null));

        jTabbedPane4.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, null, null));
        jTabbedPane3.addTab("tab1", jTabbedPane4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        deleteDataButton.setText("Delete Customer");
        deleteDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataButtonActionPerformed(evt);
            }
        });

        AddDataButton.setText("Add Customer");
        AddDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(0, 200, 254));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        displayData_Area.setColumns(20);
        displayData_Area.setRows(5);
        jScrollPane1.setViewportView(displayData_Area);

        AddStaff.setText("Add Staff");
        AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffActionPerformed(evt);
            }
        });

        DeleteStaff.setText("Delete Staff");
        DeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AddDataButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddStaff)
                                .addGap(65, 65, 65)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(LogoutButton))
                            .addComponent(deleteDataButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(DeleteStaff)
                        .addGap(58, 58, 58))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDataButton)
                    .addComponent(AddStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDataButton)
                    .addComponent(DeleteStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(44, 44, 44))
        );

        manageStaffTab.setBackground(new java.awt.Color(255, 255, 255));
        manageStaffTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, null, null));

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, null, null));
        manageStaffTab.addTab("Manage Appointments", jTabbedPane2);
        manageStaffTab.addTab("Manage Staff", jSplitPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageStaffTab)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(manageStaffTab, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void AddDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataButtonActionPerformed
        // Display the list of appointment
    displayAppointments();
    }

    private void displayAppointments() {
        Appointment[] appointments = SaloonGUI.appointments;
        StringBuilder appointmentsString = new StringBuilder();
        for (int i = 0; i < SaloonGUI.appointments.length; i++) {
            Appointment appointment = SaloonGUI.appointments[i];
            if (appointment != null) {
                Customer customer = appointments[i].getCustomer();
                Service service = appointments[i].getService();
                if (appointment.getCustomer() != null && appointment.getService() != null) {
                    appointmentsString.append("Customer: ").append(appointment.getCustomer().getName())
                            .append(", Service: ").append(appointment.getService().getName())
                            .append(", Date: ").append(appointment.getDate())
                            .append(", Time: ").append(appointment.getTime())
                            .append(", Phone Number: ").append(appointment.getCustomer().getPhoneNumber())
                            .append(", E-mail: ").append(appointment.getCustomer().getEmail())
                            .append("\n");
                }
            }
        }
        displayData_Area.setText(appointmentsString.toString());
    }//GEN-LAST:event_AddDataButtonActionPerformed

    private void deleteDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataButtonActionPerformed
    String customerName = JOptionPane.showInputDialog(this, "Enter the customer name to delete:");
    boolean customerFound = false;
    boolean appointmentFound = false;

    for (int i = 0; i < SaloonGUI.customers.length; i++) {
        if (SaloonGUI.customers[i] != null &&
            SaloonGUI.customers[i].getName().equalsIgnoreCase(customerName)) {

            SaloonGUI.customers[i] = null;
            customerFound = true;
            break;
        }
    }

    if (customerFound) {
        for (int i = 0; i < SaloonGUI.appointments.length; i++) {
            if (SaloonGUI.appointments[i] != null &&
                SaloonGUI.appointments[i].getCustomer().getName().equalsIgnoreCase(customerName)) {

                for (int j = i; j < SaloonGUI.appointments.length - 1; j++) {
                    SaloonGUI.appointments[j] = SaloonGUI.appointments[j + 1];
                }

                SaloonGUI.appointments[SaloonGUI.appointments.length - 1] = null;
                appointmentFound = true;
            }
        }

        if (appointmentFound) {
            JOptionPane.showMessageDialog(this, "Customer appointments deleted successfully!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No customer found with the given name.");
    }

    displayAppointments();
    }//GEN-LAST:event_deleteDataButtonActionPerformed

    private void AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffActionPerformed
 addStaff();
 displayStaff();
    }//GEN-LAST:event_AddStaffActionPerformed

    private void DeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStaffActionPerformed
    deleteStaff();
    displayStaff();
    }//GEN-LAST:event_DeleteStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin admin = new Admin();
                new AdminViewGUI(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataButton;
    private javax.swing.JButton AddStaff;
    private javax.swing.JButton DeleteStaff;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton deleteDataButton;
    private javax.swing.JTextArea displayData_Area;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane manageStaffTab;
    // End of variables declaration//GEN-END:variables
}
