package saloonbooking;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class SaloonGUI extends javax.swing.JFrame {

    private Customer customer; // Example instance variable
    private Appointment appointment; // Example instance variable

    public static Appointment[] appointments = new Appointment[10]; // Use an array of Appointment objects
    public static Customer[] customers = new Customer[10]; // Define the customers list
    private static int appointmentIndex = 0; // Index for the appointments array
    private static int customerIndex = 0; // Index for the customers array
    private Map<String, Double> emailToTotalCharge = new HashMap<>();

    public SaloonGUI() {
        initComponents();
    }

    public void addAppointment(Appointment appointment) {
        for (int i = 0; i < appointments.length; i++) {
            if (appointments[i] == null) {
                appointments[i] = appointment;
                appointmentIndex++;
                break;
            }
        }

    }

    public boolean isEmpty() {
        return appointmentIndex == 0;
    }

    public int getAppointmentCount() {
        return appointmentIndex;
    }

    public void reset() {
        customerNameField.setText("");
        serviceField.setSelectedItem("Service Type");
        totalChargeField.setText("");
        appointmentDateField.setText("");
        appointmentTimeField.setText("");
        emailField.setText("");
        phoneNumberField.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalChargeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        appointmentDateField = new javax.swing.JTextField();
        serviceField = new javax.swing.JComboBox<>();
        appointmentTimeField = new javax.swing.JTextField();
        viewAppointmentsButton = new javax.swing.JButton();
        bookAppointmentButton = new javax.swing.JButton();
        cancelAppointmentButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALON BOOKING SYSTEM");
        jLabel1.setOpaque(true);

        jLabel6.setText("Total Charge:");

        totalChargeField.setText("0");
        totalChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalChargeFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel2.setText("Customer Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel3.setText("Service:");

        jLabel4.setText("Appointment Date:");

        jLabel5.setText("Appointment Time:");

        customerNameField.setFont(new java.awt.Font("Myanmar Text", 2, 12)); // NOI18N
        customerNameField.setText("First & Last Name");
        customerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameFieldActionPerformed(evt);
            }
        });

        appointmentDateField.setFont(new java.awt.Font("Myanmar Text", 2, 12)); // NOI18N
        appointmentDateField.setText("dd/mm/yy");

        serviceField.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        serviceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Service Type", "Haircut", "Coloring", "Perms and Relaxer" }));
        serviceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceFieldActionPerformed(evt);
            }
        });

        appointmentTimeField.setFont(new java.awt.Font("Myanmar Text", 2, 12)); // NOI18N
        appointmentTimeField.setText("10.00 am-10.00pm");
        appointmentTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentTimeFieldActionPerformed(evt);
            }
        });

        viewAppointmentsButton.setBackground(new java.awt.Color(0, 255, 204));
        viewAppointmentsButton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        viewAppointmentsButton.setText("View Appointment");
        viewAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppointmentsButtonActionPerformed(evt);
            }
        });

        bookAppointmentButton.setBackground(new java.awt.Color(0, 255, 204));
        bookAppointmentButton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        bookAppointmentButton.setText("Book Appointment");
        bookAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentButtonActionPerformed(evt);
            }
        });

        cancelAppointmentButton.setBackground(new java.awt.Color(0, 255, 204));
        cancelAppointmentButton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        cancelAppointmentButton.setText("Cancel Appointment");
        cancelAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAppointmentButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone Number:");

        phoneNumberField.setFont(new java.awt.Font("Myanmar Text", 2, 12)); // NOI18N
        phoneNumberField.setText("01X - XXXXXXX");
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("E-mail:");

        emailField.setFont(new java.awt.Font("Myanmar Text", 2, 12)); // NOI18N
        emailField.setText("abc@gmail.com");
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelAppointmentButton)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(179, 179, 179))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serviceField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bookAppointmentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewAppointmentsButton)))
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAppointmentsButton)
                    .addComponent(bookAppointmentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelAppointmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        jMenu1.setText("Booking page");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameFieldActionPerformed
    }//GEN-LAST:event_customerNameFieldActionPerformed

    private void viewAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppointmentsButtonActionPerformed
        if (isEmpty()) {
            JOptionPane.showMessageDialog(this, "No appointment booked.");
        } else {
            StringBuilder appointmentDetails = new StringBuilder();
            for (Appointment appointment : appointments) {
                if (appointment != null) {
                    appointmentDetails.append("Customer: ").append(appointment.getCustomer().getName())
                            .append(", Service: ").append(appointment.getService().getName())
                            .append(", Charge: ").append(appointment.getService().getCharge())
                            .append(", Date: ").append(appointment.getDate())
                            .append(", Time: ").append(appointment.getTime())
                            .append(", Phone Number: ").append(appointment.getCustomer().getPhoneNumber())
                            .append(", E-mail: ").append(appointment.getCustomer().getEmail())
                            .append("\n");
                }
            }
            JOptionPane.showMessageDialog(this, appointmentDetails.toString());
        }
    }//GEN-LAST:event_viewAppointmentsButtonActionPerformed

    private void bookAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentButtonActionPerformed
        if (appointmentDateField.getText().isEmpty() && appointmentTimeField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in your information");
        } else {
            String customerName = customerNameField.getText();
            String serviceName = (String) serviceField.getSelectedItem();
            String chargeString = totalChargeField.getText().replaceAll("[^0-9.]", "");

            if (chargeString.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid total charge.");
                return;
            }

            double charge = Double.parseDouble(chargeString);
            String date = appointmentDateField.getText();
            String time = appointmentTimeField.getText();
            String phoneNumber = phoneNumberField.getText();
            String email = emailField.getText();

            Customer customer = new Customer(customerName, email, phoneNumber);
            Service service = new Service(serviceName, charge);
            Appointment appointment = new Appointment(customer, service, date, time);

            appointments[appointmentIndex] = appointment; // Add the appointment to the appointments array
            customers[customerIndex] = customer; // Add the customer to the customers array
            appointmentIndex++; // Increment appointment index
            customerIndex++; // Increment customer index

            // Calculate the new total charge
            double totalCharge = emailToTotalCharge.getOrDefault(email, 0.0) + appointment.getService().getCharge();
            emailToTotalCharge.put(email, totalCharge);

            String message = "Appointment booked succesfully!\n";
            message = message + "Your total charge is: RM " + totalCharge + "\n";
            for (Appointment amount : appointments) {
                if (amount != null && amount.getCustomer().getEmail().equals(email)) {
                    message += "Service: " + amount.getService().getName() + ", Charge: RM " + amount.getService().getCharge() + "\n";
                }
            }
            JOptionPane.showMessageDialog(this, message);
            reset();
        }
    }//GEN-LAST:event_bookAppointmentButtonActionPerformed

    private void serviceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceFieldActionPerformed
        if (serviceField.getSelectedItem().equals("Service Type")) {
            totalChargeField.setText("0");
        } else if (serviceField.getSelectedItem().equals("Haircut")) {
            totalChargeField.setText("RM 35");
        } else if (serviceField.getSelectedItem().equals("Coloring")) {
            totalChargeField.setText("RM 70");
        } else if (serviceField.getSelectedItem().equals("Perms and Relaxer")) {
            totalChargeField.setText("RM 120");
        }
        String dateText = appointmentDateField.getText();
        String timeText = appointmentTimeField.getText();

        if (dateText.isEmpty() || timeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Appointment Date and Time.", "Missing Information", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_serviceFieldActionPerformed

    private void totalChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalChargeFieldActionPerformed
    }//GEN-LAST:event_totalChargeFieldActionPerformed

    private void appointmentTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentTimeFieldActionPerformed
    }//GEN-LAST:event_appointmentTimeFieldActionPerformed

    private void cancelAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAppointmentButtonActionPerformed
        String customerName = JOptionPane.showInputDialog("Enter the customer name to cancel the appointment:");
    String date = JOptionPane.showInputDialog("Enter the date (dd/mm/yy) of the appointment to cancel:");
    boolean found = false;

    for (int i = 0; i < appointmentIndex; i++) {
        if (appointments[i] != null && appointments[i].getCustomer().getName().equals(customerName) && appointments[i].getDate().equals(date)) {
            Appointment appointmentToRemove = appointments[i]; // Store the appointment to be removed

            //Remove appointment
            for (int j = i; j < appointmentIndex - 1; j++) {
                appointments[j] = appointments[j + 1];
            }
            appointments[appointmentIndex - 1] = null;
            appointmentIndex--;
            found = true;

            Customer customer = appointmentToRemove.getCustomer(); // Get the customer from the appointment to be removed

            JOptionPane.showMessageDialog(this, "Appointment cancelled successfully!");

            // Update the total charge
            double totalCharge = emailToTotalCharge.getOrDefault(customer.getEmail(), 0.0) - appointmentToRemove.getService().getCharge();
            emailToTotalCharge.put(customer.getEmail(), totalCharge);

            // Display the new total charge
            String message = "Appointment cancelled successfully! New total charge: RM " + totalCharge + "\n";
            for (Appointment amount : appointments) {
                if (amount != null && amount.getCustomer().getEmail().equals(customer.getEmail())) {
                    message += "Service: " + amount.getService().getName() + ", Charge: RM " + amount.getService().getCharge() + "\n";
                }
            }
            JOptionPane.showMessageDialog(this, message);
            break;
        }
    }
    if (!found) {
        JOptionPane.showMessageDialog(this, "No appointment found for the given customer and date.");
    }
    }//GEN-LAST:event_cancelAppointmentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Close the current SaloonGUI frame
        this.dispose();

        // Create a new instance of the LoginPage frame
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
    }//GEN-LAST:event_emailFieldActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaloonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaloonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaloonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaloonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaloonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appointmentDateField;
    private javax.swing.JTextField appointmentTimeField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookAppointmentButton;
    private javax.swing.JButton cancelAppointmentButton;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JComboBox<String> serviceField;
    private javax.swing.JTextField totalChargeField;
    private javax.swing.JButton viewAppointmentsButton;
    // End of variables declaration//GEN-END:variables
}
